apiVersion: batch/v1
kind: Job
metadata:
  name: job-deneme
spec:
  template:
    spec:
      containers:
      - name: job-deneme
        image: alpine
        command: ['sh', '-c', 'echo JOB BASARILI BIR SEKILDE CALISTI ; sleep 5']
      restartPolicy: Never
  backoffLimit: 2
  completions: 4
  parallelism: 2
  ttlSecondsAfterFinished: 10